// Hybrid OS v6 — GitHub Pages + Supabase
const SUPABASE_URL = "https://nlsnycwlmoukxgojrkpe.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sc255Y3dsbW91a3hnb2pya3BlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA5MzQ5NjIsImV4cCI6MjA5NjUxMDk2Mn0.Q_5R8vel8YmExTY3ztk3toHBuW1xLKUjVFzKeBbIwE4";

const appConfigured = !SUPABASE_URL.includes("PASTE_") && !SUPABASE_ANON_KEY.includes("PASTE_");
const supabaseClient = appConfigured ? supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY) : null;
let currentUser = null;
let selectedPlan = "Workout A";
let baselines = {};
let equipmentMode = "full";
let currentWeekPlan = [];

const baseTemplates = {
  "Workout A": [
    { name:"Back Squat", note:"Primary compound. 3x5, RPE 7–8.", sets:3, target:"3x5", defaultWeight:"", group:"squat" },
    { name:"Clean and Press", note:"Double progression. Stay at 85 until 5/5/5.", sets:3, target:"3x5", defaultWeight:85, group:"press" },
    { name:"Romanian Deadlift", note:"Controlled hinge. Do not chase failure.", sets:2, target:"2x8", defaultWeight:"", group:"hinge" },
    { name:"Incline Dumbbell Press", note:"Upper chest. Shoulder blades down/back.", sets:2, target:"2x10", defaultWeight:"", group:"upper" },
    { name:"Hammer Curl", note:"Arms. Clean reps.", sets:2, target:"2x12", defaultWeight:"", group:"arms" },
    { name:"Zone 2 Run", note:"Post-lift: conversational pace.", sets:1, target:"10–15 min", isRun:true, defaultWeight:15 }
  ],
  "Workout B": [
    { name:"Bench Press", note:"Primary compound. Face pulls + dead bugs first.", sets:3, target:"3x5", defaultWeight:"", group:"bench" },
    { name:"Front Squat", note:"Secondary compound. Clean reps.", sets:3, target:"3x5", defaultWeight:"", group:"squat" },
    { name:"Pull-Ups", note:"Bodyweight or assisted. Track reps.", sets:3, target:"3 sets", defaultWeight:0, group:"pull" },
    { name:"Dips", note:"Add weight only when reps are owned.", sets:2, target:"2 sets", defaultWeight:0, group:"push" },
    { name:"Curl Variation", note:"Arms. Moderate volume.", sets:2, target:"2x12", defaultWeight:"", group:"arms" },
    { name:"Triceps Variation", note:"Controlled reps. No junk volume.", sets:2, target:"2x12", defaultWeight:"", group:"arms" },
    { name:"Zone 2 Run", note:"Post-lift: conversational pace.", sets:1, target:"10–15 min", isRun:true, defaultWeight:15 }
  ],
  "Run": [{ name:"Zone 2 Run", note:"RPE 4–5. Track minutes, not speed.", sets:1, target:"20–25 min", isRun:true, defaultWeight:25 }],
  "Rest": [{ name:"Walk / Mobility", note:"Family walk, easy mobility, no required training.", sets:1, target:"Optional", isRun:true, defaultWeight:0 }]
};

const substitutions = {
  hotel: {"Back Squat":"Goblet Squat","Clean and Press":"DB Clean + Push Press","Romanian Deadlift":"DB Romanian Deadlift","Bench Press":"DB Bench Press","Front Squat":"Goblet Front Squat","Pull-Ups":"Lat Pulldown / Cable Row","Dips":"DB Floor Press"},
  dumbbells: {"Back Squat":"DB Goblet Squat","Clean and Press":"DB Clean + Press","Romanian Deadlift":"DB Romanian Deadlift","Bench Press":"DB Floor Press","Front Squat":"DB Front Squat","Pull-Ups":"1-Arm DB Row","Dips":"Close-Grip Push-Up"},
  bodyweight: {"Back Squat":"Bulgarian Split Squat","Clean and Press":"Pike Push-Up","Romanian Deadlift":"Single-Leg Hip Hinge","Bench Press":"Push-Up","Front Squat":"Tempo Split Squat","Pull-Ups":"Towel Row / Doorframe Row","Dips":"Bench Dip"}
};

const defaultWeek = [
  { dow:1, day:"Mon", plan:"Workout A", detail:"Lift + 10–15 Zone 2" },
  { dow:2, day:"Tue", plan:"Run", detail:"20–25 Zone 2" },
  { dow:3, day:"Wed", plan:"Workout B", detail:"Lift + 10–15 Zone 2" },
  { dow:4, day:"Thu", plan:"Run", detail:"20–25 Zone 2" },
  { dow:5, day:"Fri", plan:"Workout A", detail:"Alternate A/B weekly + optional run" },
  { dow:6, day:"Sat", plan:"Rest", detail:"Walk, family, mobility" },
  { dow:0, day:"Sun", plan:"Rest", detail:"Check-in + recovery" }
];

const cycleInfo = {1:{type:"Build",title:"Week 1 — Establish",text:"Use clean working weights. RPE 7–8. Leave 1–3 reps in reserve."},2:{type:"Build",title:"Week 2 — Add",text:"If Week 1 reps were owned, add weight. If not, repeat."},3:{type:"Build",title:"Week 3 — Push",text:"Hardest build week. Still no grinding."},4:{type:"Deload",title:"Week 4 — Deload",text:"Reduce weight to ~80% and use 2 working sets."},5:{type:"Build",title:"Week 5 — Rebuild",text:"Second build wave."},6:{type:"Build",title:"Week 6 — Add",text:"Progress only when reps are owned."},7:{type:"Build",title:"Week 7 — Peak",text:"Strongest build week. No failure chasing."},8:{type:"Deload",title:"Week 8 — Deload",text:"Reduce weight and volume again."}};

const els = {
  setupWarning:id("setupWarning"), authView:id("authView"), appView:id("appView"), bottomNav:id("bottomNav"), logoutBtn:id("logoutBtn"), authMessage:id("authMessage"), workoutMessage:id("workoutMessage"), checkinMessage:id("checkinMessage"), prefsMessage:id("prefsMessage"), swapMessage:id("swapMessage"), todayDateLabel:id("todayDateLabel"), todayTitle:id("todayTitle"), todayDetails:id("todayDetails"), cycleLabel:id("cycleLabel"), cycleType:id("cycleType"), cycleRing:id("cycleRing"), runTarget:id("runTarget"), weeklyPlan:id("weeklyPlan"), workoutBuilder:id("workoutBuilder"), planHeading:id("planHeading"), equipmentLabel:id("equipmentLabel"), progressList:id("progressList"), historyList:id("historyList"), cycleGrid:id("cycleGrid"), cycleDetails:id("cycleDetails"), weekSummary:id("weekSummary"), autoLifts:id("autoLifts"), autoRuns:id("autoRuns"), equipmentMode:id("equipmentMode")
};
function id(x){return document.getElementById(x)}
function todayISO(){return localDateISO(new Date())}
function localDateISO(d){const y=d.getFullYear();const m=String(d.getMonth()+1).padStart(2,"0");const day=String(d.getDate()).padStart(2,"0");return `${y}-${m}-${day}`}
function weekStartISO(d=new Date()){const x=new Date(d);const diff=(x.getDay()+6)%7;x.setDate(x.getDate()-diff);return localDateISO(x)}
function getCycleWeek(){const start=new Date("2026-06-08T00:00:00");const now=new Date();const days=Math.floor((now-start)/86400000);return (Math.floor(days/7)%8)+1}
function isDeloadWeek(){return [4,8].includes(getCycleWeek())}
function isLift(p){return p==="Workout A"||p==="Workout B"}
function showMessage(el,msg,isError=false){el.textContent=msg;el.style.color=isError?"#ff3b30":"#1c1c1e"}
function setLoggedIn(loggedIn){els.authView.classList.toggle("hidden",loggedIn);els.appView.classList.toggle("hidden",!loggedIn);els.bottomNav.classList.toggle("hidden",!loggedIn);els.logoutBtn.classList.toggle("hidden",!loggedIn)}
function dateForDow(dow){const now=new Date();const monday=new Date(now);monday.setDate(now.getDate()-((now.getDay()+6)%7));const d=new Date(monday);d.setDate(monday.getDate()+(dow===0?6:dow-1));return localDateISO(d)}
function dayName(date=new Date()){return date.toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric"})}
function planForToday(){const iso=todayISO();return currentWeekPlan.find(x=>x.date===iso)?.plan || "Rest"}
function detailsForPlan(p){if(p==="Workout A")return "Squat/hinge + Clean & Press + short Zone 2.";if(p==="Workout B")return "Bench + Front Squat + Pull-Ups/Dips + arms.";if(p==="Run")return "20–25 minutes Zone 2. Conversational pace.";return "Recovery, walking, family time."}
function runTargetForPlan(p){if(isLift(p))return "10–15 Zone 2";if(p==="Run")return "20–25 Zone 2";return "Walk"}

function getTemplates(){const sub=substitutions[equipmentMode]||{};const copy=JSON.parse(JSON.stringify(baseTemplates));Object.keys(copy).forEach(plan=>copy[plan].forEach(ex=>{if(sub[ex.name]){ex.note=`Substitution for ${ex.name}. ${ex.note}`;ex.name=sub[ex.name]}}));return copy}
function getBaselineWeight(name,fallback){const row=baselines[name];return row&&row.current_working_weight!=null?row.current_working_weight:fallback}

function buildBalancedWeek(manualDate=null,manualPlan=null){let week=defaultWeek.map(x=>({...x,date:dateForDow(x.dow),manual:false})); if(manualDate&&manualPlan){const idx=week.findIndex(x=>x.date===manualDate);if(idx>=0){week[idx].plan=manualPlan;week[idx].manual=true;week[idx].detail=detailsForPlan(manualPlan)}}
  // Rebalance remaining days after manual override: keep 3 lifts and 2-4 runs; no A/A back-to-back.
  if(manualDate){const idx=week.findIndex(x=>x.date===manualDate);const before=week.slice(0,idx+1);const after=week.slice(idx+1);const liftCount=before.filter(x=>isLift(x.plan)).length;const runCount=before.filter(x=>x.plan==="Run"||isLift(x.plan)).length;let neededLifts=Math.max(0,3-liftCount);let neededRuns=Math.max(0,4-runCount);let nextLift = before.length && before[before.length-1].plan==="Workout A" ? "Workout B" : "Workout A";
    after.forEach((d,i)=>{if(d.day==="Sat"||d.day==="Sun"){d.plan="Rest";d.detail="Recovery";return} if(neededLifts>0 && (i===0 || after[i-1].plan!==nextLift)){d.plan=nextLift;d.detail=detailsForPlan(nextLift);nextLift=nextLift==="Workout A"?"Workout B":"Workout A";neededLifts--;neededRuns=Math.max(0,neededRuns-1)} else if(neededRuns>0){d.plan="Run";d.detail=detailsForPlan("Run");neededRuns--} else {d.plan="Rest";d.detail="Recovery"}});
    week=[...before,...after];
  }
  return week;
}

async function saveWeekPlan(plan){const rows=plan.map(x=>({user_id:currentUser.id,week_start:weekStartISO(),date:x.date,assigned_plan:x.plan,is_manual_override:!!x.manual}));await supabaseClient.from("weekly_plan_overrides").upsert(rows,{onConflict:"user_id,date"})}
async function loadWeekPlan(){const start=weekStartISO();const {data}=await supabaseClient.from("weekly_plan_overrides").select("*").eq("user_id",currentUser.id).eq("week_start",start);if(data&&data.length){currentWeekPlan=defaultWeek.map(x=>{const date=dateForDow(x.dow);const found=data.find(r=>r.date===date);return {...x,date,plan:found?.assigned_plan||x.plan,manual:!!found?.is_manual_override,detail:detailsForPlan(found?.assigned_plan||x.plan)}})}else{currentWeekPlan=buildBalancedWeek();await saveWeekPlan(currentWeekPlan)}}
async function resetWeekPlan(){currentWeekPlan=buildBalancedWeek();await saveWeekPlan(currentWeekPlan);renderAll();showMessage(els.swapMessage,"Week reset to default.")}
async function changeToday(plan){currentWeekPlan=buildBalancedWeek(todayISO(),plan);await saveWeekPlan(currentWeekPlan);selectedPlan=plan;renderAll();showPanel("todayPanel");showMessage(els.swapMessage,`Today changed to ${plan}. Rest of week rebalanced.`)}

function renderAll(){renderTop();renderWeeklyPlan();renderCycleGrid();renderWorkoutBuilder();renderCheckinCounts();}
function renderTop(){const wk=getCycleWeek();selectedPlan=planForToday();els.todayDateLabel.textContent=dayName();els.todayTitle.textContent=selectedPlan;els.todayDetails.textContent=detailsForPlan(selectedPlan);els.cycleLabel.textContent=`Week ${wk}`;els.cycleType.textContent=cycleInfo[wk].type;els.cycleRing.textContent=wk;els.runTarget.textContent=runTargetForPlan(selectedPlan);els.weekSummary.textContent=`${cycleInfo[wk].title}: ${cycleInfo[wk].text}`;document.querySelectorAll(".swap-pill").forEach(b=>b.classList.toggle("active",b.dataset.plan===selectedPlan));els.planHeading.textContent=selectedPlan;els.equipmentLabel.textContent=`Equipment: ${equipmentModeLabel()}`}
function equipmentModeLabel(){return {full:"Full gym",hotel:"Hotel gym",dumbbells:"Dumbbells only",bodyweight:"Bodyweight"}[equipmentMode]||"Full gym"}
function renderWeeklyPlan(){els.weeklyPlan.innerHTML=currentWeekPlan.map(item=>{const active=item.date===todayISO();return `<article class="day-card ${active?"active":""} ${item.manual?"manual":""}" data-plan="${item.plan}" data-date="${item.date}"><div><strong>${item.day} · ${item.plan}</strong><span>${item.detail}</span></div><div class="day-tag">${active?"Today":item.manual?"Changed":"Open"}</div></article>`}).join("")}
function renderCycleGrid(activeWeek=getCycleWeek()){els.cycleGrid.innerHTML=Object.keys(cycleInfo).map(k=>{const wk=Number(k),info=cycleInfo[wk];return `<button class="cycle-week ${wk===activeWeek?"active":""} ${info.type==="Deload"?"deload":""}" data-week="${wk}"><strong>${wk}</strong><span>${info.type}</span></button>`}).join("");renderCycleDetails(activeWeek)}
function renderCycleDetails(wk){const info=cycleInfo[wk];els.cycleDetails.innerHTML=`<h3>${info.title}</h3><p class="muted small">${info.text}</p><p class="progress-decision">Rule: hit all target reps → increase. Miss once → repeat. Miss twice → reduce 10%.</p>`}
function rowHtml(setIndex,ex){const isRun=!!ex.isRun;const baseline=getBaselineWeight(ex.name,ex.defaultWeight);const repsDefault=isRun?"":(ex.target.includes("8")?8:ex.target.includes("10")?10:ex.target.includes("12")?12:5);const w=baseline===0?"0":(baseline||"");return `<div class="set-row"><span class="set-num">${setIndex+1}</span><input class="set-weight" type="number" inputmode="decimal" step="2.5" placeholder="${isRun?"target":"lb"}" value="${w}"/><input class="set-reps" type="number" inputmode="numeric" placeholder="${isRun?"done":"reps"}" value="${isRun?"":repsDefault}"/><input class="set-rpe" type="number" inputmode="decimal" step="0.5" placeholder="RPE"/><button class="remove-set" type="button">×</button></div>`}
function renderWorkoutBuilder(){const templates=getTemplates();const plan=templates[selectedPlan]||templates["Workout A"];els.workoutBuilder.innerHTML=plan.map((ex,i)=>`<article class="exercise-card" data-exercise-name="${ex.name}" data-is-run="${ex.isRun?"true":"false"}"><div class="exercise-head"><div class="exercise-name">${ex.name}</div><div class="exercise-note">${ex.note}</div><span class="badge">${ex.target}</span></div><div class="set-header"><span>Set</span><span>${ex.isRun?"Target":"Weight"}</span><span>${ex.isRun?"Done":"Reps"}</span><span>RPE</span><span></span></div><div class="sets-container">${Array.from({length:ex.sets}).map((_,idx)=>rowHtml(idx,ex)).join("")}</div><button class="add-set" type="button">+ Add set</button></article>`).join("");bindRowHighlightListeners()}
function bindRowHighlightListeners(){document.querySelectorAll(".set-row").forEach(row=>{const evalRow=()=>{const w=row.querySelector(".set-weight").value;const r=row.querySelector(".set-reps").value;row.classList.toggle("filled",!!(w||r))};evalRow();row.querySelectorAll("input").forEach(i=>i.addEventListener("input",evalRow))})}
function showPanel(panelId){document.querySelectorAll(".panel").forEach(p=>p.classList.add("hidden"));id(panelId).classList.remove("hidden");document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.panel===panelId));window.scrollTo({top:0})}

function collectExerciseRows(){const exercises=[];document.querySelectorAll(".exercise-card").forEach(card=>{const name=card.dataset.exerciseName;const isRun=card.dataset.isRun==="true";const rows=[];card.querySelectorAll(".set-row").forEach((row,idx)=>{const weight=Number(row.querySelector(".set-weight").value||0);const reps=Number(row.querySelector(".set-reps").value||0);const rpe=Number(row.querySelector(".set-rpe").value||0);if(weight>0||reps>0||rpe>0)rows.push({set_number:idx+1,weight,reps,rpe})});if(rows.length)exercises.push({name,isRun,rows})});return exercises}
function progressionDecision(exerciseName,weight,repsArray){const lower=exerciseName.toLowerCase();const hitAll=repsArray.length>=3&&repsArray.every(r=>r>=5);const lowerBody=lower.includes("squat")||lower.includes("deadlift");const cleanPress=lower.includes("clean")&&lower.includes("press");if(isDeloadWeek())return {nextWeight:Math.round(weight*.8),decision:"Deload: use ~80% and 2 working sets.",hitAll};if(cleanPress)return hitAll?{nextWeight:weight+5,decision:"Clean & Press owned. Add 5 lb next exposure.",hitAll}:{nextWeight:weight,decision:"Clean & Press double progression: repeat this weight.",hitAll};if(hitAll)return {nextWeight:weight+(lowerBody?5:5),decision:`All reps hit. Add ${lowerBody?"5":"2.5–5"} lb next exposure.`,hitAll};return {nextWeight:weight,decision:"Repeat weight until target reps are owned.",hitAll}}
async function saveWorkout(){if(!currentUser)return;const exercises=collectExerciseRows();const notes=id("workoutNotes").value;if(!exercises.length&&!notes.trim())return showMessage(els.workoutMessage,"Enter at least one set or notes.",true);const {data:workout,error:workoutError}=await supabaseClient.from("workout_logs").insert({user_id:currentUser.id,date:todayISO(),workout_type:selectedPlan,cycle_week:getCycleWeek(),is_deload:isDeloadWeek(),notes}).select().single();if(workoutError)return showMessage(els.workoutMessage,workoutError.message,true);const setRows=[],runRows=[];exercises.forEach(ex=>{if(ex.isRun){const first=ex.rows[0];runRows.push({user_id:currentUser.id,date:todayISO(),run_type:ex.name,target_minutes:first.weight||0,completed_minutes:first.reps||0,rpe:first.rpe||0,notes:`${selectedPlan} · ${notes||""}`})}else{ex.rows.forEach(row=>setRows.push({workout_log_id:workout.id,exercise_name:ex.name,weight:row.weight,reps:row.reps,set_number:row.set_number,rpe:row.rpe,completed:true}))}});if(setRows.length){const {error}=await supabaseClient.from("exercise_sets").insert(setRows);if(error)return showMessage(els.workoutMessage,error.message,true)}if(runRows.length){const {error}=await supabaseClient.from("run_logs").insert(runRows);if(error)return showMessage(els.workoutMessage,error.message,true)}for(const ex of exercises.filter(e=>!e.isRun)){const usable=ex.rows.filter(r=>r.reps>0);if(!usable.length)continue;const weight=usable[usable.length-1].weight;const repsArray=usable.map(r=>r.reps);const {nextWeight,decision,hitAll}=progressionDecision(ex.name,weight,repsArray);const existing=baselines[ex.name];let missCount=hitAll?0:((existing?.miss_count||0)+1);let finalNextWeight=nextWeight;let finalDecision=decision;if(!hitAll&&missCount>=2&&!isDeloadWeek()){finalNextWeight=Math.round(weight*.9);finalDecision="Missed twice: reduce load about 10% and rebuild.";missCount=0}await supabaseClient.from("lift_baselines").upsert({user_id:currentUser.id,exercise_name:ex.name,current_working_weight:finalNextWeight,target_sets:3,target_reps:5,last_result:`${weight} x ${repsArray.join(",")}`,miss_count:missCount,next_decision:finalDecision,updated_at:new Date().toISOString()},{onConflict:"user_id,exercise_name"})}showMessage(els.workoutMessage,"Saved. Your workout memory updated.");await loadProgress();await loadHistory();await renderCheckinCounts();renderWorkoutBuilder()}
async function loadProgress(){const {data,error}=await supabaseClient.from("lift_baselines").select("*").eq("user_id",currentUser.id).order("updated_at",{ascending:false});if(error){els.progressList.innerHTML=`<p class="muted">${error.message}</p>`;return}baselines={};(data||[]).forEach(row=>baselines[row.exercise_name]=row);els.progressList.innerHTML=(data&&data.length)?data.map(row=>`<article class="progress-item"><strong>${row.exercise_name}</strong><div>Next target: ${row.current_working_weight??0} lb</div><div class="muted small">Last: ${row.last_result||"—"} · Misses: ${row.miss_count||0}</div><div class="progress-decision">${row.next_decision||"Repeat until owned."}</div></article>`).join(""):`<p class="muted">No lift baselines yet. Log a workout to start.</p>`}
async function loadHistory(){const [workouts,runs]=await Promise.all([supabaseClient.from("workout_logs").select("*").eq("user_id",currentUser.id).order("created_at",{ascending:false}).limit(10),supabaseClient.from("run_logs").select("*").eq("user_id",currentUser.id).order("created_at",{ascending:false}).limit(5)]);const workoutHtml=(workouts.data||[]).map(row=>`<article class="history-item"><strong>${row.date} · ${row.workout_type}</strong><span class="muted small">Week ${row.cycle_week} ${row.is_deload?"· Deload":"· Build"}</span><p class="muted small">${row.notes||""}</p></article>`).join("");const runHtml=(runs.data||[]).map(row=>`<article class="history-item"><strong>${row.date} · ${row.run_type}</strong><span class="muted small">${row.completed_minutes||0}/${row.target_minutes||0} min · RPE ${row.rpe||"—"}</span></article>`).join("");els.historyList.innerHTML=workoutHtml+runHtml||`<p class="muted">No history yet.</p>`}
async function renderCheckinCounts(){if(!currentUser)return;const start=weekStartISO();const endDate=new Date(start);endDate.setDate(endDate.getDate()+7);const end=localDateISO(endDate);const [w,r]=await Promise.all([supabaseClient.from("workout_logs").select("*").eq("user_id",currentUser.id).gte("date",start).lt("date",end),supabaseClient.from("run_logs").select("*").eq("user_id",currentUser.id).gte("date",start).lt("date",end)]);const lifts=(w.data||[]).filter(x=>isLift(x.workout_type)).length;const runs=(r.data||[]).filter(x=>(x.completed_minutes||0)>0).length;els.autoLifts.textContent=`${lifts}/3`;els.autoRuns.textContent=`${runs}/4`;return {lifts,runs}}
async function saveCheckin(){const counts=await renderCheckinCounts();const {error}=await supabaseClient.from("weekly_checkins").insert({user_id:currentUser.id,week_start:weekStartISO(),body_weight:Number(id("bodyWeight").value||0),waist:Number(id("waist").value||0),lifts_completed:counts?.lifts||0,runs_completed:counts?.runs||0,protein_rating:id("proteinRating").value,recovery_rating:id("recoveryRating").value,notes:id("checkinNotes").value});if(error)return showMessage(els.checkinMessage,error.message,true);showMessage(els.checkinMessage,"Check-in saved.")}
async function loadPrefs(){const {data}=await supabaseClient.from("user_preferences").select("*").eq("user_id",currentUser.id).maybeSingle();equipmentMode=data?.equipment_mode||"full";els.equipmentMode.value=equipmentMode}
async function savePrefs(){equipmentMode=els.equipmentMode.value;await supabaseClient.from("user_preferences").upsert({user_id:currentUser.id,equipment_mode:equipmentMode,updated_at:new Date().toISOString()},{onConflict:"user_id"});showMessage(els.prefsMessage,"Equipment saved.");renderAll()}
async function signUp(){const email=id("email").value.trim();const password=id("password").value;if(!email||!password)return showMessage(els.authMessage,"Enter email and password.",true);const {error}=await supabaseClient.auth.signUp({email,password});showMessage(els.authMessage,error?error.message:"Account created. Log in.",!!error)}
async function signIn(){const email=id("email").value.trim();const password=id("password").value;if(!email||!password)return showMessage(els.authMessage,"Enter email and password.",true);const {data,error}=await supabaseClient.auth.signInWithPassword({email,password});if(error)return showMessage(els.authMessage,error.message,true);currentUser=data.user;setLoggedIn(true);await bootApp()}
async function signOut(){await supabaseClient.auth.signOut();currentUser=null;setLoggedIn(false)}
function setupEvents(){id("signupBtn").addEventListener("click",signUp);id("loginBtn").addEventListener("click",signIn);id("logoutBtn").addEventListener("click",signOut);id("saveWorkoutBtn").addEventListener("click",saveWorkout);id("saveCheckinBtn").addEventListener("click",saveCheckin);id("savePrefsBtn").addEventListener("click",savePrefs);id("startWorkoutBtn").addEventListener("click",()=>showPanel("workoutPanel"));id("resetWeekBtn").addEventListener("click",resetWeekPlan);document.querySelectorAll(".swap-pill").forEach(btn=>btn.addEventListener("click",()=>changeToday(btn.dataset.plan)));document.querySelectorAll(".nav-item").forEach(btn=>btn.addEventListener("click",()=>showPanel(btn.dataset.panel)));els.weeklyPlan.addEventListener("click",e=>{const card=e.target.closest(".day-card");if(!card)return;selectedPlan=card.dataset.plan;renderWorkoutBuilder();showPanel("workoutPanel")});els.cycleGrid.addEventListener("click",e=>{const btn=e.target.closest(".cycle-week");if(btn)renderCycleGrid(Number(btn.dataset.week))});els.workoutBuilder.addEventListener("click",e=>{if(e.target.classList.contains("add-set")){const card=e.target.closest(".exercise-card");const templates=getTemplates();const ex=Object.values(templates).flat().find(x=>x.name===card.dataset.exerciseName)||{name:card.dataset.exerciseName,isRun:card.dataset.isRun==="true",defaultWeight:""};const container=card.querySelector(".sets-container");container.insertAdjacentHTML("beforeend",rowHtml(container.children.length,ex));bindRowHighlightListeners()}if(e.target.classList.contains("remove-set")){const row=e.target.closest(".set-row");const container=row.parentElement;if(container.children.length>1)row.remove();[...container.children].forEach((child,index)=>child.querySelector(".set-num").textContent=index+1)}})}
async function bootApp(){await loadPrefs();await loadWeekPlan();await loadProgress();renderAll();await loadHistory();showPanel("todayPanel")}
async function init(){setupEvents();if(!appConfigured){els.setupWarning.classList.remove("hidden");return}const {data}=await supabaseClient.auth.getUser();if(data.user){currentUser=data.user;setLoggedIn(true);await bootApp()}else{setLoggedIn(false)}}
init();
